name: Build Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  build:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          pip install pyserial 

      - name: Verify serial installation
        run: |
          python -c "import serial; print(f'serial version: {serial.__version__}')"

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --icon assets/logo.ico `
          --add-data "tools;tools" `
          --add-data "assets;assets" `
          --name KitFW_Flasher `
          --hidden-import serial `
          --hidden-import serial.tools.list_ports `
          main.py

      - name: Rename Artifact
        run: |
          move dist\KitFW_Flasher.exe dist\KitFW_Flasher_${{ github.ref_name }}.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/KitFW_Flasher_${{ github.ref_name }}.exe